name: cop1-checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # every hour

jobs:
  check-keywords:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch target page
        id: check
        run: |
          RESPONSE=$(curl -sL "https://linktr.ee/cop1besancon")

          if [[ "$RESPONSE" == *"13 septembre"* && "$RESPONSE" == *"13-septembre"* ]]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Send email with Resend
        if: steps.check.outputs.found == 'false'
        run: |
          curl -X POST "https://api.resend.com/emails" \
            -H "Authorization: Bearer ${{ secrets.RESEND_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "from": "onboarding@resend.dev",
              "to": ["massyl.amarni@outlook.fr"],
              "subject": "COP1",
              "text": "Updated !"
            }'
